# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-10 18:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calibration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cal_by', models.CharField(max_length=200)),
                ('cal_date', models.DateField()),
                ('notes', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_number', models.CharField(max_length=200)),
                ('serial_number', models.CharField(max_length=200)),
                ('manufacturer', models.CharField(max_length=200)),
                ('model', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=200)),
                ('cal_interval', models.IntegerField()),
                ('initial_condition', models.IntegerField()),
                ('cal_cert_location', models.FilePathField(verbose_name='intranet\\LAB (testing)\\Cal')),
                ('manual_location', models.FilePathField(verbose_name='intranet\\LAB (testing)\\Cal')),
                ('picture', models.ImageField(upload_to='')),
                ('picture_front', models.BooleanField()),
                ('meets_pctest_test_specs', models.BooleanField()),
                ('mesure_uncertainty_included', models.BooleanField()),
                ('initial_accessories_included', models.CharField(max_length=200)),
                ('placed_in_service_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag_type', models.CharField(max_length=200)),
                ('flag_content', models.CharField(max_length=200)),
                ('flag_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calbase.Equipment')),
            ],
        ),
        migrations.AddField(
            model_name='calibration',
            name='cal_asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calbase.Equipment'),
        ),
    ]
