# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 15:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(blank=True, null=True, upload_to='picture/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='Calibration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cal_by', models.CharField(max_length=200, null=True)),
                ('cal_17025_check', models.CharField(choices=[('Yes', 'Yes'), ('Wavier List', 'Wavier List')], max_length=20, null=True)),
                ('cal_date', models.DateField(null=True)),
                ('mesure_uncertainty_included', models.BooleanField(default=False)),
                ('a2la_Cal', models.BooleanField(default=False)),
                ('qc_test_by', models.CharField(blank=True, max_length=200, null=True)),
                ('qc_test_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(choices=[('Cali', 'Cali'), ('MD', 'MD'), ('Out', 'Out')], max_length=20, null=True)),
                ('cal_cert_location', models.FileField(blank=True, null=True, upload_to='cal_cert/')),
                ('notes', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_number', models.CharField(max_length=200, null=True, unique=True)),
                ('serial_number', models.CharField(max_length=200, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('model', models.CharField(max_length=200, null=True)),
                ('cal_interval', models.IntegerField(null=True, verbose_name='calibration interval (year)')),
                ('initial_condition', models.CharField(choices=[('new', 'new'), ('used', 'used'), ('lease/rental', 'lease/rental')], max_length=20, null=True)),
                ('manual_location', models.FileField(blank=True, null=True, upload_to='manual/')),
                ('initial_accessories_included', models.CharField(max_length=200, null=True)),
                ('placed_in_service_date', models.DateField(null=True)),
                ('location', models.CharField(choices=[('Cali', 'Cali'), ('MD', 'MD'), ('Out', 'Out')], max_length=20, null=True)),
                ('latest_calibration_date', models.DateField(blank=True, null=True)),
                ('cal_due_date', models.DateField(blank=True, null=True, verbose_name='calibration due date')),
                ('is_flagged', models.CharField(blank=True, default='', editable=False, max_length=100)),
                ('department', models.ManyToManyField(to='calbase.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag_type', models.CharField(max_length=200, null=True)),
                ('flag_content', models.CharField(max_length=200, null=True)),
                ('flag_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calbase.Equipment')),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('equip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calbase.Equipment')),
            ],
        ),
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='equipment',
            name='used_for_test',
            field=models.ManyToManyField(to='calbase.Tests'),
        ),
        migrations.AddField(
            model_name='description',
            name='equip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calbase.Equipment'),
        ),
        migrations.AddField(
            model_name='calibration',
            name='cal_asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calbase.Equipment'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='equip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calbase.Equipment'),
        ),
    ]
