# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-11 21:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calbase', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='cal_cert_location',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='cal_interval',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='description',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='initial_accessories_included',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='initial_condition',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='manual_location',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='manufacturer',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='meets_pctest_test_specs',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='mesure_uncertainty_included',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='model',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='picture_front',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='placed_in_service_date',
        ),
    ]
