# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calbase', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='description',
            name='equip',
        ),
        migrations.RemoveField(
            model_name='manufacturer',
            name='equip',
        ),
        migrations.AddField(
            model_name='equipment',
            name='description',
            field=models.ManyToManyField(to='calbase.Description'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='manufacturer',
            field=models.ManyToManyField(to='calbase.Manufacturer'),
        ),
    ]
