# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-17 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calbase', '0002_auto_20160811_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='calibration',
            name='notes',
            field=models.CharField(max_length=200),
        ),
    ]
