# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calbase', '0003_auto_20160928_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capabilities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='calibration',
            name='cal_17025_check',
            field=models.CharField(choices=[('Yes', 'Yes'), ('Wavier List', 'Wavier List')], max_length=20, null=True, verbose_name='Calibration 17205 Checked?'),
        ),
        migrations.AlterField(
            model_name='calibration',
            name='cal_by',
            field=models.CharField(max_length=200, null=True, verbose_name='Calibration by'),
        ),
        migrations.AlterField(
            model_name='calibration',
            name='cal_cert_location',
            field=models.FileField(blank=True, null=True, upload_to='cal_cert/', verbose_name='Calibration Certification File'),
        ),
        migrations.AlterField(
            model_name='calibration',
            name='cal_date',
            field=models.DateField(null=True, verbose_name='Calibration date (YYYY-MM-DD)'),
        ),
        migrations.AlterField(
            model_name='calibration',
            name='location',
            field=models.CharField(choices=[('Cali', 'Cali'), ('MD', 'MD'), ('Out', 'Out')], max_length=20, null=True, verbose_name='Equipment Location'),
        ),
        migrations.AlterField(
            model_name='calibration',
            name='qc_test_by',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='QC Test by'),
        ),
        migrations.AlterField(
            model_name='calibration',
            name='qc_test_date',
            field=models.DateField(blank=True, null=True, verbose_name='QC Test date (YYYY-MM-DD)'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='capabilities',
            field=models.ManyToManyField(to='calbase.Capabilities'),
        ),
    ]
