# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-22 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calbase', '0003_auto_20160817_1118'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='equipment',
            name='a2la_Cal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='equipment',
            name='cal_interval',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='description',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='initial_accessories_included',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='initial_condition',
            field=models.CharField(choices=[('new', 'new'), ('used', 'used'), ('lease/rental', 'lease/rental')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='inservice',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='equipment',
            name='manual_location',
            field=models.FilePathField(null=True, path='intranet\\LAB (testing)\\Cal'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='manufacturer',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='meets_pctest_test_specs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='equipment',
            name='mesure_uncertainty_included',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='equipment',
            name='model',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='picture',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='equipment',
            name='picture_taken',
            field=models.CharField(choices=[('front', 'front'), ('back', 'back')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='placed_in_service_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='calibration',
            name='cal_by',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='calibration',
            name='cal_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='calibration',
            name='notes',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='asset_number',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='serial_number',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='flag',
            name='flag_content',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='flag',
            name='flag_type',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='used_for_test',
            field=models.ManyToManyField(null=True, to='calbase.Tests'),
        ),
    ]
