# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 22:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calbase', '0004_auto_20160928_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='desc',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='manuf',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
