# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-22 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calbase', '0004_auto_20160822_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='used_for_test',
            field=models.ManyToManyField(to='calbase.Tests'),
        ),
    ]
