# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-22 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calbase', '0005_auto_20160822_1212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='inservice',
        ),
        migrations.AlterField(
            model_name='equipment',
            name='description',
            field=models.CharField(default=' ', max_length=200),
        ),
    ]
