# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calbase', '0006_auto_20160822_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='manual_location',
            field=models.FilePathField(null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='picture',
            field=models.FileField(null=True, upload_to='picture/%Y/%m/%d'),
        ),
    ]
