# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calbase', '0007_auto_20160823_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='cal_cert_location',
            field=models.FilePathField(null=True),
        ),
    ]
