# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calbase', '0008_equipment_cal_cert_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='cal_cert_location',
            field=models.FilePathField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='manual_location',
            field=models.FilePathField(max_length=300, null=True),
        ),
    ]
