# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calbase', '0009_auto_20160823_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='cal_cert_location',
            field=models.FilePathField(match='.*\\.(pdf)$', max_length=300, null=True, path='H:\\Internal PCTEST Applications\\intranet\\LAB (testing)\\Cal'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='initial_condition',
            field=models.CharField(choices=[('new', 'new'), ('used', 'used'), ('lease/rental', 'lease/rental')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='manual_location',
            field=models.FilePathField(match='.*\\.(pdf)$', max_length=300, null=True, path='H:\\Internal PCTEST Applications\\intranet\\LAB (testing)\\Cal'),
        ),
    ]
