# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calbase', '0011_cart_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='location',
            field=models.CharField(choices=[('Cali', 'Cali'), ('MD', 'MD'), ('Out', 'Out')], max_length=20, null=True),
        ),
    ]
