# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calbase', '0013_auto_20160824_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='picture',
            field=models.ImageField(null=True, upload_to='picture/%Y/%m/%d'),
        ),
    ]
