# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 19:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calbase', '0014_auto_20160826_1128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='cal_cert_location',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='manual_location',
        ),
    ]
