# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-09 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calbase', '0015_auto_20160826_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='picture/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
