# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-12 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calbase', '0017_auto_20160912_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='latest_calibration_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
