# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-20 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calbase', '0019_auto_20160920_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='asset_number',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
