# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-21 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calbase', '0022_auto_20160920_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='a2la_Cal',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='meets_pctest_test_specs',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='mesure_uncertainty_included',
        ),
        migrations.AddField(
            model_name='calibration',
            name='a2la_Cal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='calibration',
            name='mesure_uncertainty_included',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='calibration',
            name='qc_test_by',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='calibration',
            name='qc_test_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
