# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-22 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calbase', '0024_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='department',
        ),
        migrations.AddField(
            model_name='equipment',
            name='department',
            field=models.ManyToManyField(to='calbase.Department'),
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='manufacturer',
        ),
        migrations.AddField(
            model_name='equipment',
            name='manufacturer',
            field=models.ManyToManyField(to='calbase.Manufacturer'),
        ),
    ]
