# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calbase', '0027_attachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='picture_taken',
        ),
        migrations.AlterField(
            model_name='equipment',
            name='cal_due_date',
            field=models.DateField(blank=True, null=True, verbose_name='calibration due date'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='cal_interval',
            field=models.IntegerField(null=True, verbose_name='calibration interval (year)'),
        ),
    ]
